#!/bin/bash

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Starting nginx service
sudo service nginx start

# Allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
sudo mv /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "<html>\n<head><title>Holberton School</title></head>\n<body>\nHolberton School\n</body>\n</html>" | sudo tee /var/www/html/index.nginx-debian.html

# Restarting nginx
sudo service nginx restart

echo -e "\nCompleted. ✅ \n"

